### PR TITLE
Document FORCE_COLOR

### PR DESCRIPTION
**Pull request by ssbarnea**
Document use of FORCE_COLOR variable which forces enablement of
coloring and ignore the detection logic.

There are other similar option used like CLI_COLOR, PY_COLORS but
that one is by far the most popular option. This complements
the NO_COLOR option with missed to cover for the opposite use-case
when it was designed.

### CODE REVIEW

**Comment by ssbarnea** [comment]
No idea why this fails, but considering I cannot click it I hope one the cores will fix CI.

**Comment by tashian** [comment]
Thanks @ssbarnea, not sure what happened with the deploy bot, but when I merged it it worked.

**Comment by ssbarnea** [comment]
@tashian Few years later I discover that the PR was not really merged but closed. Any idea why?

**Comment by ssbarnea** [comment]
I am visiting https://clig.dev/#environment-variables page and I do not see any mention of `FORCE_COLOR`.

**Pull request closed without merging**
