### PR TITLE
Add documentation section with revised man page advice

### PR DESCRIPTION
**Pull request by aanand**
After some thought, I think this gets closer to how I feel about man pages and terminal-based documentation.

### CODE REVIEW

**Comment by tashian** [comment]
Nice @aanand. I especially like the distinction between help text and docs.
One potential improvement: it would be nice to list some helpful tools or common workflows for making and publishing documentation.

**Comment by bfirsh** [comment]
This is very good, although I miss the hot take. :)

Agreed the distinction between docs and help text is useful. This could be tied back to [the different types of docs](https://www.writethedocs.org/videos/eu/2017/the-four-kinds-of-documentation-and-why-you-need-to-understand-what-they-are-daniele-procida/): help text is for reference; documentation is for learning, understanding, and achieving particular goals (in addition to reference).

**Comment by aanand** [comment]
I like the distinctions drawn there - it would seem that help text is largely _problem-oriented_, while documentation is more broad, but more likely to include _learning-oriented_ material. @evazorro - would be interested in your thoughts here!

**Comment by evazorro** [comment]
Yes, agreed with all of the above! I've read and liked that Divio article before. I would consider help text a reference ("information-oriented"). Good web-based documentation will have all four categories. I'm not sure how much we want to get into documentation best practices/recommendations here (linking to that article, for example); I think what you have is sufficient.

**Pull request merged**
